version: "3.3"

services:
  nats-server:
    image: nats
    restart: always
    ports:
      - "4222:4222"
    networks:
      - betnominetwork
    # entrypoint: "/gnatsd -DV"
    # expose:
    #   - "4222"
  
  envoy:
    image: envoyproxy/envoy:v1.22.0
    ports:
      - "10000:10000"
    networks:
      - betnominetwork
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=betnomiadmin
      - POSTGRES_PASSWORD=asd279364kk
      - POSTGRES_DB=betnomi
    ports:
      - 5432:5432
    networks:
      - betnominetwork
    volumes:
      - pgdb:/var/lib/postgresql/data/
  
  user-service:
    build:
      context: services/user-service
      dockerfile: Dockerfile
    container_name: "user-service-container"
    ports:
      - 9091:9091
    depends_on:
      - database
    networks:
      - betnominetwork

  transaction-service:
    build:
      context: services/transaction-service
      dockerfile: Dockerfile
    container_name: "transaction-service-container"
    ports:
      - 9092:9092
    depends_on:
      - database
    networks:
      - betnominetwork

  # cache:
  #   image: redis
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes: 
  #     - cache:/data

volumes:
  pgdb:
  cache:
    driver: local

networks:
  betnominetwork:
    driver: bridge
